name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk:latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        apk add build-base git bash cmake pkgconfig texinfo

    - name: Compile project
      run: |
        make -j$(getconf _NPROCESSORS_ONLN)
